name: sawdust_codegen
description: Generates filler text classes from YAML
version: 1.0.0
author: Scott Hyndman <scott@yarrow.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.36.3
  build: ^1.1.0
  meta: ^1.1.0
  path: ^1.6.2
  sawdust:
    path: ../sawdust

dev_dependencies:
  build_runner: ^1.4.0
  build_test: ^0.10.8
  logging: ^0.11.3
  pedantic: ^1.7.0
  test: ^1.6.0
